// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm9Gcd4ggvD36W6s-n4OKPP5AVSeDo8dM',
    appId: '1:425933510706:web:c69b47d5f314d00903042b',
    messagingSenderId: '425933510706',
    projectId: 'sarthak-my-sub',
    authDomain: 'sarthak-my-sub.firebaseapp.com',
    storageBucket: 'sarthak-my-sub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1kIH0-YKkIOMniePbcMZnHG0keBE1LdU',
    appId: '1:425933510706:android:9be4e7aeb041515c03042b',
    messagingSenderId: '425933510706',
    projectId: 'sarthak-my-sub',
    storageBucket: 'sarthak-my-sub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8awEFpvva4gmMl1NMiUcv9RNixnRNUrY',
    appId: '1:425933510706:ios:06c4e6b7e6eaaa7203042b',
    messagingSenderId: '425933510706',
    projectId: 'sarthak-my-sub',
    storageBucket: 'sarthak-my-sub.appspot.com',
    iosBundleId: 'com.example.sub1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8awEFpvva4gmMl1NMiUcv9RNixnRNUrY',
    appId: '1:425933510706:ios:9325a7467c8b493d03042b',
    messagingSenderId: '425933510706',
    projectId: 'sarthak-my-sub',
    storageBucket: 'sarthak-my-sub.appspot.com',
    iosBundleId: 'com.example.sub1.RunnerTests',
  );
}
